// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ICreature} from "./interfaces/ICreature.sol";
import {GenePool} from "./GenePool.sol";
import {CreatureFactory} from "./CreatureFactory.sol";

/// @dev Minimal interface for XCMRouter yield simulation.
interface IYieldSimulator {
    function deployedCapital(address creature) external view returns (uint256);
    function simulateReturnForCreature(address creature, address asset, int256 yieldAmount) external;
}

/// @title Ecosystem
/// @notice Top-level entry point for the ALIVE protocol. All user capital
///         flows through this contract. It manages the lifecycle of the
///         entire artificial-life colony:
///
///           Deposit → Allocate → Feed → Harvest → Evolve → Reallocate
///
///         Users deposit stablecoins and earn yield generated by the colony
///         of autonomous Creature strategies.
contract Ecosystem {
    using SafeERC20 for IERC20;

    // ----------------------------------------------------------------
    // Epoch phases
    // ----------------------------------------------------------------

    enum Phase {
        IDLE,
        FEEDING,
        HARVESTING,
        EVOLVING,
        ALLOCATING
    }

    // ----------------------------------------------------------------
    // State
    // ----------------------------------------------------------------

    /// @notice User deposit tracking (shares-based model).
    mapping(address => uint256) public shares;
    uint256 public totalShares;

    /// @notice Total stablecoin capital held by the Ecosystem vault.
    uint256 public totalCapital;

    /// @notice Current epoch.
    uint256 public currentEpoch;

    /// @notice Epoch timing.
    uint256 public epochDuration; // in blocks
    uint256 public lastEpochBlock;

    /// @notice Active Creature population.
    address[] public activeCreatures;

    /// @notice The fitness score from last evolution (creature → score).
    mapping(address => uint256) public latestFitness;

    /// @notice Sum of all fitness scores (for weighted allocation).
    uint256 public totalFitness;

    /// @notice Core dependencies.
    GenePool public genePool;
    CreatureFactory public factory;
    IERC20 public stablecoin;

    /// @notice XCM router for yield simulation (SIMULATION mode).
    IYieldSimulator public xcmRouter;

    /// @notice Owner / deployer — limited to initial setup.
    address public owner;

    /// @notice Current phase in the epoch state machine.
    Phase public phase;

    /// @notice Track total yield generated across all epochs.
    int256 public totalYieldGenerated;

    // ----------------------------------------------------------------
    // Events
    // ----------------------------------------------------------------

    event Deposited(address indexed user, uint256 amount, uint256 sharesIssued);
    event Withdrawn(address indexed user, uint256 amount, uint256 sharesBurned);
    event EpochAdvanced(uint256 indexed epoch, Phase phase);
    event CapitalAllocated(uint256 totalAllocated, uint256 creatureCount);
    event InitialCreaturesSpawned(uint256 count);
    event CreatureRegistered(address indexed creature);

    // ----------------------------------------------------------------
    // Modifiers
    // ----------------------------------------------------------------

    modifier onlyOwner() {
        require(msg.sender == owner, "Ecosystem: caller not owner");
        _;
    }

    modifier inPhase(Phase expected) {
        require(phase == expected, "Ecosystem: wrong phase");
        _;
    }

    // ----------------------------------------------------------------
    // Constructor
    // ----------------------------------------------------------------

    constructor(
        address _stablecoin,
        address _factory,
        uint256 _epochDuration
    ) {
        stablecoin = IERC20(_stablecoin);
        factory = CreatureFactory(_factory);
        epochDuration = _epochDuration;
        lastEpochBlock = block.number;
        owner = msg.sender;
        phase = Phase.IDLE;
    }

    /// @notice Set the GenePool address. Called once after GenePool is deployed.
    function setGenePool(address _genePool) external onlyOwner {
        require(address(genePool) == address(0), "Ecosystem: genePool already set");
        genePool = GenePool(_genePool);
    }

    /// @notice Set the XCM router for yield simulation.
    function setXCMRouter(address _xcmRouter) external onlyOwner {
        xcmRouter = IYieldSimulator(_xcmRouter);
    }

    /// @notice Register a newly seeded Creature into the active population.
    ///         Only callable by the GenePool (via injectSeed).
    /// @param creature The address of the Creature contract to register.
    function registerCreature(address creature) external {
        require(msg.sender == address(genePool), "Ecosystem: caller not genePool");
        activeCreatures.push(creature);
        emit CreatureRegistered(creature);
    }

    // ----------------------------------------------------------------
    // User-Facing: Deposit / Withdraw
    // ----------------------------------------------------------------

    /// @notice Deposit stablecoins into the ecosystem.
    ///         Shares are minted proportionally to the current vault value.
    /// @param amount Amount of stablecoins to deposit.
    function deposit(uint256 amount) external {
        require(amount > 0, "Ecosystem: zero deposit");

        stablecoin.safeTransferFrom(msg.sender, address(this), amount);

        uint256 newShares;
        if (totalShares == 0 || totalCapital == 0) {
            // First depositor: 1 token = 1 share
            newShares = amount;
        } else {
            // shares = amount * totalShares / totalCapital
            newShares = (amount * totalShares) / totalCapital;
        }
        require(newShares > 0, "Ecosystem: deposit too small");

        shares[msg.sender] += newShares;
        totalShares += newShares;
        totalCapital += amount;

        emit Deposited(msg.sender, amount, newShares);
    }

    /// @notice Withdraw stablecoins from the ecosystem.
    ///         Burns shares and returns proportional capital + yield.
    ///         Uses the live system value (vault + creature balances).
    /// @param shareAmount Number of shares to burn.
    function withdraw(uint256 shareAmount) external {
        require(shareAmount > 0, "Ecosystem: zero withdraw");
        require(shares[msg.sender] >= shareAmount, "Ecosystem: insufficient shares");

        // Compute value from total system value (vault + creatures)
        uint256 systemValue = _totalSystemValue();
        uint256 value = (shareAmount * systemValue) / totalShares;

        // Ensure ecosystem vault has enough; if not, recall from creatures
        uint256 vaultBal = stablecoin.balanceOf(address(this));
        if (value > vaultBal) {
            _recallCapital(value - vaultBal);
        }

        shares[msg.sender] -= shareAmount;
        totalShares -= shareAmount;
        totalCapital = _totalSystemValue() - value; // will be updated after transfer

        stablecoin.safeTransfer(msg.sender, value);

        // Re-sync after transfer
        totalCapital = _totalSystemValue();

        emit Withdrawn(msg.sender, value, shareAmount);
    }

    // ----------------------------------------------------------------
    // Epoch State Machine
    // ----------------------------------------------------------------

    /// @notice Advance through the epoch cycle. Each call moves the phase
    ///         forward by one step. Anyone can call once the epoch duration
    ///         has elapsed (for IDLE → FEEDING).
    function advanceEpoch() external {
        if (phase == Phase.IDLE) {
            require(
                block.number >= lastEpochBlock + epochDuration,
                "Ecosystem: epoch not elapsed"
            );
            phase = Phase.FEEDING;
            currentEpoch++;
            emit EpochAdvanced(currentEpoch, Phase.FEEDING);
            _feedAll();
            phase = Phase.HARVESTING;
            emit EpochAdvanced(currentEpoch, Phase.HARVESTING);

        } else if (phase == Phase.HARVESTING) {
            _harvestAll();
            phase = Phase.EVOLVING;
            emit EpochAdvanced(currentEpoch, Phase.EVOLVING);

        } else if (phase == Phase.EVOLVING) {
            _evolve();
            phase = Phase.ALLOCATING;
            emit EpochAdvanced(currentEpoch, Phase.ALLOCATING);

        } else if (phase == Phase.ALLOCATING) {
            _allocateCapital();
            phase = Phase.IDLE;
            lastEpochBlock = block.number;
            emit EpochAdvanced(currentEpoch, Phase.IDLE);

        } else {
            revert("Ecosystem: invalid phase");
        }
    }

    // ----------------------------------------------------------------
    // Initial Creatures
    // ----------------------------------------------------------------

    /// @notice Deploy the initial seed population.
    ///         Called by the owner or seeder at launch time.
    /// @param dnaList Array of DNA configs for the initial population.
    function spawnInitialCreatures(ICreature.DNA[] calldata dnaList) external onlyOwner {
        require(activeCreatures.length == 0, "Ecosystem: already spawned");
        require(dnaList.length > 0, "Ecosystem: empty dna list");

        for (uint256 i = 0; i < dnaList.length; i++) {
            address creature = factory.deploy(
                dnaList[i],
                0, // generation 0
                address(0), // no parent1
                address(0), // no parent2
                currentEpoch
            );
            activeCreatures.push(creature);
        }

        emit InitialCreaturesSpawned(dnaList.length);
    }

    // ----------------------------------------------------------------
    // Internal: Capital Management
    // ----------------------------------------------------------------

    /// @dev Recall capital from creatures back to the vault.
    ///      Used when a user withdraws and the vault doesn't have enough.
    ///      Proportionally recalls from all alive creatures, then does a
    ///      second pass to cover any rounding shortfall.
    function _recallCapital(uint256 needed) internal {
        uint256 totalCreatureBal = 0;
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            totalCreatureBal += stablecoin.balanceOf(activeCreatures[i]);
        }
        if (totalCreatureBal == 0) return;

        uint256 remaining = needed;

        // First pass: proportional recall
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            uint256 creatureBal = stablecoin.balanceOf(activeCreatures[i]);
            if (creatureBal == 0) continue;

            uint256 recallAmount = (needed * creatureBal) / totalCreatureBal;
            if (recallAmount > creatureBal) recallAmount = creatureBal;
            if (recallAmount == 0) continue;

            ICreature(activeCreatures[i]).returnCapital(recallAmount);
            if (remaining > recallAmount) {
                remaining -= recallAmount;
            } else {
                remaining = 0;
            }
        }

        // Second pass: cover rounding shortfall from any creature with balance
        if (remaining > 0) {
            for (uint256 i = 0; i < activeCreatures.length; i++) {
                if (remaining == 0) break;
                uint256 creatureBal = stablecoin.balanceOf(activeCreatures[i]);
                if (creatureBal == 0) continue;

                uint256 extra = remaining > creatureBal ? creatureBal : remaining;
                ICreature(activeCreatures[i]).returnCapital(extra);
                remaining -= extra;
            }
        }
    }

    // ----------------------------------------------------------------
    // Internal: Phase Execution
    // ----------------------------------------------------------------

    /// @dev Feed all active Creatures — they deploy capital via XCM.
    function _feedAll() internal {
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            if (ICreature(activeCreatures[i]).isAlive()) {
                ICreature(activeCreatures[i]).feed();
            }
        }
    }

    /// @dev Harvest all active Creatures — they collect returns.
    ///      First simulates XCM yields (DNA-dependent) so creatures get
    ///      their capital back with strategy-dependent returns, then
    ///      calls harvest() so creatures record the performance.
    function _harvestAll() internal {
        // Simulate yields: return deployed capital + DNA-dependent yield
        _simulateYields();

        int256 epochYield = 0;
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            if (ICreature(activeCreatures[i]).isAlive()) {
                ICreature(activeCreatures[i]).harvest();
                (int256 lr, , , , ) = ICreature(activeCreatures[i]).getPerformance();
                epochYield += lr;
            }
        }
        totalYieldGenerated += epochYield;

        // Update totalCapital to reflect TOTAL system value (vault + creatures)
        totalCapital = _totalSystemValue();
    }

    /// @dev Simulate XCM yields with DNA-dependent returns.
    ///      Each creature gets a different yield based on their strategy DNA:
    ///        - poolType determines base yield (RESTAKING > STAKING > VAULT > AMM > LENDING > STABLE_SWAP)
    ///        - riskCeiling determines variance (higher risk = wider outcomes)
    ///        - maxSlippage penalizes sloppy execution
    ///      Pseudo-randomness per creature per epoch ensures outcome diversity.
    function _simulateYields() internal {
        if (address(xcmRouter) == address(0)) return;

        for (uint256 i = 0; i < activeCreatures.length; i++) {
            address creature = activeCreatures[i];
            if (!ICreature(creature).isAlive()) continue;

            uint256 deployed = xcmRouter.deployedCapital(creature);
            if (deployed == 0) continue;

            ICreature.DNA memory dna = ICreature(creature).getDNA();
            int256 yieldAmount = _computeCreatureYield(creature, dna, deployed);

            xcmRouter.simulateReturnForCreature(
                creature,
                address(stablecoin),
                yieldAmount
            );
        }
    }

    /// @dev Compute yield for a creature based on its DNA strategy.
    ///      Returns SIGNED yield amount — positive = gain, negative = loss.
    ///
    ///      Yield formula (per epoch):
    ///        base_yield  = pool_type_base   (50–250 bps)
    ///        penalty     = maxSlippage / 5  (2–100 bps)
    ///        noise       = random in [0, riskCeiling * 150] bps
    ///        total_bps   = base - penalty - riskRange/2 + noise
    ///
    ///      Risk-reward trade-off: high-risk strategies can go negative,
    ///      creating drawdowns that differentiate fitness scores.
    function _computeCreatureYield(
        address creature,
        ICreature.DNA memory dna,
        uint256 deployed
    ) internal view returns (int256) {
        // Base yield per pool type (basis points per epoch)
        // Deliberately moderate so risky strategies can go negative
        uint256 baseYieldBps;
        if (dna.poolType == 0) baseYieldBps = 120;       // AMM_LP
        else if (dna.poolType == 1) baseYieldBps = 80;   // LENDING
        else if (dna.poolType == 2) baseYieldBps = 180;  // STAKING
        else if (dna.poolType == 3) baseYieldBps = 150;  // VAULT
        else if (dna.poolType == 4) baseYieldBps = 50;   // STABLE_SWAP
        else if (dna.poolType == 5) baseYieldBps = 250;  // RESTAKING
        else baseYieldBps = 100;

        // Slippage penalty: higher maxSlippage = worse execution
        uint256 slippagePenalty = uint256(dna.maxSlippage) / 5;

        // Risk-based variance using pseudo-randomness
        uint256 noise = uint256(keccak256(abi.encodePacked(
            block.prevrandao, creature, currentEpoch
        )));
        // Wider risk range so high-risk creatures can swing negative
        uint256 riskRange = uint256(dna.riskCeiling) * 150;
        uint256 noiseOffset = noise % (riskRange + 1);

        // Center noise: base - penalty - riskRange/2 + noiseOffset
        // High riskCeiling → riskRange/2 can exceed base → negative yields
        int256 totalBps = int256(baseYieldBps)
            - int256(slippagePenalty)
            - int256(riskRange / 2)
            + int256(noiseOffset);

        // Cap losses at -500 bps (5%) per epoch to avoid instant wipeout
        if (totalBps < -500) totalBps = -500;

        return (int256(deployed) * totalBps) / 10_000;
    }

    /// @dev Run evolution via GenePool — score, select, breed, kill.
    function _evolve() internal {
        if (activeCreatures.length < 2) return;

        // Run GenePool's evolution algorithm
        address[] memory newPop = genePool.runEvolution(activeCreatures, currentEpoch);

        // Store fitness scores from the evolution run into latestFitness
        totalFitness = 0;
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            uint256 score = genePool.getFitness(activeCreatures[i]);
            latestFitness[activeCreatures[i]] = score;
            totalFitness += score;
        }

        // Process kills: GenePool stores pending kills for us to execute
        address[] memory kills = genePool.getPendingKills();
        for (uint256 i = 0; i < kills.length; i++) {
            ICreature(kills[i]).kill();
            // Clear fitness for killed creatures
            totalFitness -= latestFitness[kills[i]];
            latestFitness[kills[i]] = 0;
        }

        // Replace active population
        delete activeCreatures;
        for (uint256 i = 0; i < newPop.length; i++) {
            activeCreatures.push(newPop[i]);
        }

        // Reclaim capital returned by killed creatures + track total system value
        totalCapital = _totalSystemValue();
    }

    /// @dev Allocate capital to surviving + newborn Creatures, weighted by fitness.
    ///      First recalls ALL capital from creatures back to the vault, then
    ///      redistributes based on fitness weights. This prevents the vault from
    ///      running dry when creatures hold capital from prior epochs.
    function _allocateCapital() internal {
        uint256 creatureCount = activeCreatures.length;
        if (creatureCount == 0) return;

        // ---- Step 1: Recall ALL capital from creatures into the vault ----
        for (uint256 i = 0; i < creatureCount; i++) {
            uint256 creatureBal = stablecoin.balanceOf(activeCreatures[i]);
            if (creatureBal > 0 && ICreature(activeCreatures[i]).isAlive()) {
                ICreature(activeCreatures[i]).returnCapital(creatureBal);
            }
        }

        // Now the vault holds all system capital
        uint256 vaultBalance = stablecoin.balanceOf(address(this));
        if (vaultBalance == 0) return;

        // Collect fitness scores from the last evolution run
        // For the first epoch (before any evolution), use equal weighting
        totalFitness = 0;

        if (currentEpoch <= 1) {
            // Equal allocation for first epoch
            uint256 perCreature = vaultBalance / creatureCount;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (perCreature > 0 && ICreature(activeCreatures[i]).isAlive()) {
                    stablecoin.forceApprove(activeCreatures[i], perCreature);
                    ICreature(activeCreatures[i]).receiveCapital(perCreature);
                }
            }
            emit CapitalAllocated(vaultBalance, creatureCount);
            // Update totalCapital to reflect total system value
            totalCapital = _totalSystemValue();
            return;
        }

        // ---- Step 2: Fitness-weighted re-distribution ----
        uint256[] memory weights = new uint256[](creatureCount);
        uint256 totalWeight = 0;

        for (uint256 i = 0; i < creatureCount; i++) {
            if (!ICreature(activeCreatures[i]).isAlive()) continue;

            // Use real fitness scores from the evolution engine
            uint256 w = latestFitness[activeCreatures[i]];
            if (w == 0) w = 1; // minimum weight so every creature gets something

            weights[i] = w;
            totalWeight += w;
        }

        if (totalWeight == 0) {
            // Fallback to equal
            uint256 perCreature = vaultBalance / creatureCount;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (perCreature > 0 && ICreature(activeCreatures[i]).isAlive()) {
                    stablecoin.forceApprove(activeCreatures[i], perCreature);
                    ICreature(activeCreatures[i]).receiveCapital(perCreature);
                }
            }
        } else {
            uint256 allocated = 0;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (!ICreature(activeCreatures[i]).isAlive()) continue;

                uint256 amount = (vaultBalance * weights[i]) / totalWeight;
                if (amount > 0) {
                    stablecoin.forceApprove(activeCreatures[i], amount);
                    ICreature(activeCreatures[i]).receiveCapital(amount);
                    allocated += amount;
                }
            }
            // Handle dust — give remainder to first alive creature
            if (allocated < vaultBalance) {
                uint256 dust = vaultBalance - allocated;
                for (uint256 i = 0; i < creatureCount; i++) {
                    if (ICreature(activeCreatures[i]).isAlive()) {
                        stablecoin.forceApprove(activeCreatures[i], dust);
                        ICreature(activeCreatures[i]).receiveCapital(dust);
                        break;
                    }
                }
            }
        }

        emit CapitalAllocated(vaultBalance, creatureCount);

        // After allocation, totalCapital must reflect total system value
        totalCapital = _totalSystemValue();
    }

    // ----------------------------------------------------------------
    // Internal: System Value
    // ----------------------------------------------------------------

    /// @dev Compute total system value = ecosystem vault + all creature balances.
    ///      This ensures shareValue always accounts for capital held by creatures.
    function _totalSystemValue() internal view returns (uint256) {
        uint256 total = stablecoin.balanceOf(address(this));
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            total += stablecoin.balanceOf(activeCreatures[i]);
            // Include capital currently deployed to XCM strategies
            if (address(xcmRouter) != address(0)) {
                total += xcmRouter.deployedCapital(activeCreatures[i]);
            }
        }
        return total;
    }

    // ----------------------------------------------------------------
    // Views
    // ----------------------------------------------------------------

    /// @notice Get the number of active Creatures.
    function getCreatureCount() external view returns (uint256) {
        return activeCreatures.length;
    }

    /// @notice Get all active Creature addresses.
    function getActiveCreatures() external view returns (address[] memory) {
        return activeCreatures;
    }

    /// @notice Get ecosystem state summary.
    ///         deposits = total system value (vault + creature balances).
    function getEcosystemState()
        external
        view
        returns (
            uint256 deposits,
            uint256 epoch,
            uint256 creatureCount,
            int256 yieldGenerated,
            Phase currentPhase
        )
    {
        return (
            _totalSystemValue(),
            currentEpoch,
            activeCreatures.length,
            totalYieldGenerated,
            phase
        );
    }

    /// @notice Compute the value of a user's shares in stablecoin terms.
    ///         Uses live system-wide balance (vault + all creatures).
    function shareValue(address user) external view returns (uint256) {
        if (totalShares == 0) return 0;
        uint256 systemValue = _totalSystemValue();
        return (shares[user] * systemValue) / totalShares;
    }

    /// @notice Get total system value (vault + all creature balances).
    function totalSystemValue() external view returns (uint256) {
        return _totalSystemValue();
    }
}
