// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ICreature} from "./interfaces/ICreature.sol";
import {GenePool} from "./GenePool.sol";
import {CreatureFactory} from "./CreatureFactory.sol";

/// @title Ecosystem
/// @notice Top-level entry point for the ALIVE protocol. All user capital
///         flows through this contract. It manages the lifecycle of the
///         entire artificial-life colony:
///
///           Deposit → Allocate → Feed → Harvest → Evolve → Reallocate
///
///         Users deposit stablecoins and earn yield generated by the colony
///         of autonomous Creature strategies.
contract Ecosystem {
    using SafeERC20 for IERC20;

    // ----------------------------------------------------------------
    // Epoch phases
    // ----------------------------------------------------------------

    enum Phase {
        IDLE,
        FEEDING,
        HARVESTING,
        EVOLVING,
        ALLOCATING
    }

    // ----------------------------------------------------------------
    // State
    // ----------------------------------------------------------------

    /// @notice User deposit tracking (shares-based model).
    mapping(address => uint256) public shares;
    uint256 public totalShares;

    /// @notice Total stablecoin capital held by the Ecosystem vault.
    uint256 public totalCapital;

    /// @notice Current epoch.
    uint256 public currentEpoch;

    /// @notice Epoch timing.
    uint256 public epochDuration; // in blocks
    uint256 public lastEpochBlock;

    /// @notice Active Creature population.
    address[] public activeCreatures;

    /// @notice The fitness score from last evolution (creature → score).
    mapping(address => uint256) public latestFitness;

    /// @notice Sum of all fitness scores (for weighted allocation).
    uint256 public totalFitness;

    /// @notice Core dependencies.
    GenePool public genePool;
    CreatureFactory public factory;
    IERC20 public stablecoin;

    /// @notice Owner / deployer — limited to initial setup.
    address public owner;

    /// @notice Current phase in the epoch state machine.
    Phase public phase;

    /// @notice Track total yield generated across all epochs.
    int256 public totalYieldGenerated;

    // ----------------------------------------------------------------
    // Events
    // ----------------------------------------------------------------

    event Deposited(address indexed user, uint256 amount, uint256 sharesIssued);
    event Withdrawn(address indexed user, uint256 amount, uint256 sharesBurned);
    event EpochAdvanced(uint256 indexed epoch, Phase phase);
    event CapitalAllocated(uint256 totalAllocated, uint256 creatureCount);
    event InitialCreaturesSpawned(uint256 count);

    // ----------------------------------------------------------------
    // Modifiers
    // ----------------------------------------------------------------

    modifier onlyOwner() {
        require(msg.sender == owner, "Ecosystem: caller not owner");
        _;
    }

    modifier inPhase(Phase expected) {
        require(phase == expected, "Ecosystem: wrong phase");
        _;
    }

    // ----------------------------------------------------------------
    // Constructor
    // ----------------------------------------------------------------

    constructor(
        address _stablecoin,
        address _factory,
        uint256 _epochDuration
    ) {
        stablecoin = IERC20(_stablecoin);
        factory = CreatureFactory(_factory);
        epochDuration = _epochDuration;
        lastEpochBlock = block.number;
        owner = msg.sender;
        phase = Phase.IDLE;
    }

    /// @notice Set the GenePool address. Called once after GenePool is deployed.
    function setGenePool(address _genePool) external onlyOwner {
        require(address(genePool) == address(0), "Ecosystem: genePool already set");
        genePool = GenePool(_genePool);
    }

    // ----------------------------------------------------------------
    // User-Facing: Deposit / Withdraw
    // ----------------------------------------------------------------

    /// @notice Deposit stablecoins into the ecosystem.
    ///         Shares are minted proportionally to the current vault value.
    /// @param amount Amount of stablecoins to deposit.
    function deposit(uint256 amount) external {
        require(amount > 0, "Ecosystem: zero deposit");

        stablecoin.safeTransferFrom(msg.sender, address(this), amount);

        uint256 newShares;
        if (totalShares == 0 || totalCapital == 0) {
            // First depositor: 1 token = 1 share
            newShares = amount;
        } else {
            // shares = amount * totalShares / totalCapital
            newShares = (amount * totalShares) / totalCapital;
        }
        require(newShares > 0, "Ecosystem: deposit too small");

        shares[msg.sender] += newShares;
        totalShares += newShares;
        totalCapital += amount;

        emit Deposited(msg.sender, amount, newShares);
    }

    /// @notice Withdraw stablecoins from the ecosystem.
    ///         Burns shares and returns proportional capital + yield.
    /// @param shareAmount Number of shares to burn.
    function withdraw(uint256 shareAmount) external {
        require(shareAmount > 0, "Ecosystem: zero withdraw");
        require(shares[msg.sender] >= shareAmount, "Ecosystem: insufficient shares");

        // value = shareAmount * totalCapital / totalShares
        uint256 value = (shareAmount * totalCapital) / totalShares;

        shares[msg.sender] -= shareAmount;
        totalShares -= shareAmount;
        totalCapital -= value;

        stablecoin.safeTransfer(msg.sender, value);

        emit Withdrawn(msg.sender, value, shareAmount);
    }

    // ----------------------------------------------------------------
    // Epoch State Machine
    // ----------------------------------------------------------------

    /// @notice Advance through the epoch cycle. Each call moves the phase
    ///         forward by one step. Anyone can call once the epoch duration
    ///         has elapsed (for IDLE → FEEDING).
    function advanceEpoch() external {
        if (phase == Phase.IDLE) {
            require(
                block.number >= lastEpochBlock + epochDuration,
                "Ecosystem: epoch not elapsed"
            );
            phase = Phase.FEEDING;
            currentEpoch++;
            emit EpochAdvanced(currentEpoch, Phase.FEEDING);
            _feedAll();
            phase = Phase.HARVESTING;
            emit EpochAdvanced(currentEpoch, Phase.HARVESTING);

        } else if (phase == Phase.HARVESTING) {
            _harvestAll();
            phase = Phase.EVOLVING;
            emit EpochAdvanced(currentEpoch, Phase.EVOLVING);

        } else if (phase == Phase.EVOLVING) {
            _evolve();
            phase = Phase.ALLOCATING;
            emit EpochAdvanced(currentEpoch, Phase.ALLOCATING);

        } else if (phase == Phase.ALLOCATING) {
            _allocateCapital();
            phase = Phase.IDLE;
            lastEpochBlock = block.number;
            emit EpochAdvanced(currentEpoch, Phase.IDLE);

        } else {
            revert("Ecosystem: invalid phase");
        }
    }

    // ----------------------------------------------------------------
    // Initial Creatures
    // ----------------------------------------------------------------

    /// @notice Deploy the initial seed population.
    ///         Called by the owner or seeder at launch time.
    /// @param dnaList Array of DNA configs for the initial population.
    function spawnInitialCreatures(ICreature.DNA[] calldata dnaList) external onlyOwner {
        require(activeCreatures.length == 0, "Ecosystem: already spawned");
        require(dnaList.length > 0, "Ecosystem: empty dna list");

        for (uint256 i = 0; i < dnaList.length; i++) {
            address creature = factory.deploy(
                dnaList[i],
                0, // generation 0
                address(0), // no parent1
                address(0), // no parent2
                currentEpoch
            );
            activeCreatures.push(creature);
        }

        emit InitialCreaturesSpawned(dnaList.length);
    }

    // ----------------------------------------------------------------
    // Internal: Phase Execution
    // ----------------------------------------------------------------

    /// @dev Feed all active Creatures — they deploy capital via XCM.
    function _feedAll() internal {
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            if (ICreature(activeCreatures[i]).isAlive()) {
                ICreature(activeCreatures[i]).feed();
            }
        }
    }

    /// @dev Harvest all active Creatures — they collect returns.
    function _harvestAll() internal {
        int256 epochYield = 0;
        for (uint256 i = 0; i < activeCreatures.length; i++) {
            if (ICreature(activeCreatures[i]).isAlive()) {
                ICreature(activeCreatures[i]).harvest();
                (int256 lr, , , , ) = ICreature(activeCreatures[i]).getPerformance();
                epochYield += lr;
            }
        }
        totalYieldGenerated += epochYield;

        // Update totalCapital to reflect actual vault balance
        totalCapital = stablecoin.balanceOf(address(this));
    }

    /// @dev Run evolution via GenePool — score, select, breed, kill.
    function _evolve() internal {
        if (activeCreatures.length < 2) return;

        // Run GenePool's evolution algorithm
        address[] memory newPop = genePool.runEvolution(activeCreatures, currentEpoch);

        // Process kills: GenePool stores pending kills for us to execute
        address[] memory kills = genePool.getPendingKills();
        for (uint256 i = 0; i < kills.length; i++) {
            ICreature(kills[i]).kill();
        }

        // Replace active population
        delete activeCreatures;
        for (uint256 i = 0; i < newPop.length; i++) {
            activeCreatures.push(newPop[i]);
        }

        // Reclaim capital returned by killed creatures
        totalCapital = stablecoin.balanceOf(address(this));
    }

    /// @dev Allocate capital to surviving + newborn Creatures, weighted by fitness.
    function _allocateCapital() internal {
        uint256 creatureCount = activeCreatures.length;
        if (creatureCount == 0 || totalCapital == 0) return;

        // Collect fitness scores from the last evolution run
        // For the first epoch (before any evolution), use equal weighting
        totalFitness = 0;

        if (currentEpoch <= 1) {
            // Equal allocation for first epoch
            uint256 perCreature = totalCapital / creatureCount;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (perCreature > 0 && ICreature(activeCreatures[i]).isAlive()) {
                    stablecoin.forceApprove(activeCreatures[i], perCreature);
                    ICreature(activeCreatures[i]).receiveCapital(perCreature);
                }
            }
            emit CapitalAllocated(totalCapital, creatureCount);
            return;
        }

        // Fitness-weighted allocation
        // Use the IEvolutionEngine results cached by GenePool if available
        // For simplicity, weight by epochsSurvived * (1 + cumulativeReturn normalization)
        uint256[] memory weights = new uint256[](creatureCount);
        uint256 totalWeight = 0;

        for (uint256 i = 0; i < creatureCount; i++) {
            if (!ICreature(activeCreatures[i]).isAlive()) continue;

            (, int256 cr, uint256 es, , ) = ICreature(activeCreatures[i]).getPerformance();

            // Weight = epochsSurvived + bonus for positive cumulative return
            // Shift cumulative return to avoid negatives (add a base of 1000)
            uint256 w = es + 1; // at least 1
            if (cr > 0) {
                w += uint256(cr) / 1e18; // scale down if using 18-decimal tokens
            }
            weights[i] = w;
            totalWeight += w;
        }

        if (totalWeight == 0) {
            // Fallback to equal
            uint256 perCreature = totalCapital / creatureCount;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (perCreature > 0 && ICreature(activeCreatures[i]).isAlive()) {
                    stablecoin.forceApprove(activeCreatures[i], perCreature);
                    ICreature(activeCreatures[i]).receiveCapital(perCreature);
                }
            }
        } else {
            uint256 allocated = 0;
            for (uint256 i = 0; i < creatureCount; i++) {
                if (!ICreature(activeCreatures[i]).isAlive()) continue;

                uint256 amount = (totalCapital * weights[i]) / totalWeight;
                if (amount > 0) {
                    stablecoin.forceApprove(activeCreatures[i], amount);
                    ICreature(activeCreatures[i]).receiveCapital(amount);
                    allocated += amount;
                }
            }
            // Handle dust — give remainder to first alive creature
            uint256 dust = totalCapital - allocated;
            if (dust > 0 && creatureCount > 0) {
                for (uint256 i = 0; i < creatureCount; i++) {
                    if (ICreature(activeCreatures[i]).isAlive()) {
                        stablecoin.forceApprove(activeCreatures[i], dust);
                        ICreature(activeCreatures[i]).receiveCapital(dust);
                        break;
                    }
                }
            }
        }

        emit CapitalAllocated(totalCapital, creatureCount);
    }

    // ----------------------------------------------------------------
    // Views
    // ----------------------------------------------------------------

    /// @notice Get the number of active Creatures.
    function getCreatureCount() external view returns (uint256) {
        return activeCreatures.length;
    }

    /// @notice Get all active Creature addresses.
    function getActiveCreatures() external view returns (address[] memory) {
        return activeCreatures;
    }

    /// @notice Get ecosystem state summary.
    function getEcosystemState()
        external
        view
        returns (
            uint256 deposits,
            uint256 epoch,
            uint256 creatureCount,
            int256 yieldGenerated,
            Phase currentPhase
        )
    {
        return (
            totalCapital,
            currentEpoch,
            activeCreatures.length,
            totalYieldGenerated,
            phase
        );
    }

    /// @notice Compute the value of a user's shares in stablecoin terms.
    function shareValue(address user) external view returns (uint256) {
        if (totalShares == 0) return 0;
        return (shares[user] * totalCapital) / totalShares;
    }
}
